USE HealthCareData2025

CREATE TABLE diabetic_data (
    encounter_id                NVARCHAR(50) PRIMARY KEY,
    patient_nbr                 NVARCHAR(50),
    race                        NVARCHAR(255),
    gender                      NVARCHAR(50),
    age                         NVARCHAR(50),
    weight                      NVARCHAR(50),
    admission_type_id           NVARCHAR(50),
    discharge_disposition_id    NVARCHAR(50),
    admission_source_id         NVARCHAR(50),
    time_in_hospital            NVARCHAR(50),
    payer_code                  NVARCHAR(50),
    medical_specialty           NVARCHAR(255),
    num_lab_procedures          NVARCHAR(50),
    num_procedures              NVARCHAR(50),
    num_medications             NVARCHAR(50),
    number_outpatient           NVARCHAR(50),
    number_emergency            NVARCHAR(50),
    number_inpatient            NVARCHAR(50),
    diag_1                      NVARCHAR(10),
    diag_2                      NVARCHAR(10),
    diag_3                      NVARCHAR(10),
    number_diagnoses            NVARCHAR(50),
    max_glu_serum               NVARCHAR(50),
    A1Cresult                   NVARCHAR(50),
    metformin                   NVARCHAR(50),
    repaglinide                 NVARCHAR(50),
    nateglinide                 NVARCHAR(50),
    chlorpropamide              NVARCHAR(50),
    glimepiride                 NVARCHAR(50),
    acetohexamide               NVARCHAR(50),
    glipizide                   NVARCHAR(50),
    glyburide                   NVARCHAR(50),
    tolbutamide                 NVARCHAR(50),
    pioglitazone                NVARCHAR(50),
    rosiglitazone               NVARCHAR(50),
    acarbose                    NVARCHAR(50),
    miglitol                    NVARCHAR(50),
    troglitazone                NVARCHAR(50),
    tolazamide                  NVARCHAR(50),
    examide                     NVARCHAR(50),
    citoglipton                 NVARCHAR(50),
    insulin                     NVARCHAR(50),
    [glyburide-metformin]       NVARCHAR(50),
    [glipizide-metformin]       NVARCHAR(50),
    [glimepiride-pioglitazone]  NVARCHAR(50),
    [metformin-rosiglitazone]   NVARCHAR(50),
    [metformin-pioglitazone]    NVARCHAR(50),
    change                      NVARCHAR(50),
    diabetesMed                 NVARCHAR(50),
    readmitted                  NVARCHAR(50)
);
GO
